const { model, Schema } = require("mongoose");

const productSchema = new Schema(
  {
    name: { type: String, required: true },
    picture: { type: String, required: true },
    description: { type: String },
    productCategory: {
      type: String,
      required: true,
      enum: [
        "Computers and Laptops",
        "Smartphones and Accessories",
        "Audio and Video Equipment",
        "Cameras and Photography Gear",
        "Gaming Consoles and Accessories",
        "Home Appliances",
        "Clothing",
        "Shoes and Footwear",
        "Jewelry and Watches",
        "Bags and Luggage",
        "Sunglasses and EyewearAccessories",
        "Furniture",
        "Home Decor and Accessories",
        "Kitchen and Dining Essentials",
        "Bedding and Bath",
        "Lighting and Fixtures",
        "Appliances",
        "Fiction and Non-fiction Books",
        "Textbooks and Educational Materials",
        "Movies",
        "Music",
        "E-books and Audiobooks",
        "Musical Instruments",
        "Exercise Equipment",
        "Sports Gear and Apparel",
        "Outdoor Gear and Camping Equipment",
        "Bicycles and Accessories",
        "Fitness Trackers and Wearables",
        "Sports Memorabilia",
        "Skincare and Cosmetics",
        "Haircare and Styling Products",
        "Personal Care and Hygiene",
        "Vitamins and Supplements",
        "Fragrances and Perfumes",
        "Wellness and Relaxation Products",
        "Board Games and Puzzles",
        "Action Figures and Collectibles",
        "Building Blocks and Construction Sets",
        "Dolls and Accessories",
        "Educational Toys",
        "Outdoor Play Equipment",
        "Car Parts and Accessories",
        "Motorcycles and Scooters",
        "Tools and Equipment",
        "Car Care and Maintenance",
        "GPS and Navigation Systems",
        "Car Electronics",
      ],
    },
    provider: { type: Schema.Types.ObjectId, ref: "User", required: true },
    requester: { type: Schema.Types.ObjectId, ref: "User" },
    bbAmount: { type: Number, required: true },
    reserved: { type: Boolean, default: false },
  },
  { timestamps: true }
);

const Product = model("Product", productSchema);

module.exports = Product;
